### ISSUE TITLE
Jumbled Weapon screen UI

### ISSUE THREAD

**Issue by RuffGhannor** [ANTIBigBoss/MGS3-Cheat-Trainer-GUI#2]
The Weapons UI buttons, input boxes and text aren't formatted, so they appear all jumbled together. This only happens to this screen . Also thanks for the trainer, besides this issue it works wonderfully!
![imagem_2024-03-02_223135653](https://github.com/ANTIBigBoss/MGS3-Cheat-Trainer-GUI/assets/55282486/1a562798-f2c9-4791-a504-93d8f6fb4178)

**Comment by ANTIBigBoss** [comment]
Oh man that's using something from my like very first test version I'll try and get that fixed up this week. What happened before it triggered like this?

**Comment by RuffGhannor** [comment]
I installed the trainer, it launched and the menu screen opened, I clicked "Weapons" and it was like that, thought it might have gotten corrupted during install but no luck, I reinstalled it and it's like that on first launch! The buttons and boxes do work, but I can't know exactly what I'm doing.

**Comment by ANTIBigBoss** [comment]
Yeah no worries was just trying to see if there was a pattern or not one other person had this happen a couple months back so it's been hard to figure out what's causing it. I think I might have a solution I'll push either tonight or tomorrow hopefully!

**Comment by ANTIBigBoss** [comment]
Alright @RuffGhannor I pushed a new update to the trainer it should update next time it's ran lmk if the issue persists!

**Comment by RuffGhannor** [comment]
Hey, I downloaded the update and checked it, now it works great! Can see all the buttons, images, edit text and click all of them without issues. Thanks for fixing it!
![imagem_2024-03-06_213307525](https://github.com/ANTIBigBoss/MGS3-Cheat-Trainer-GUI/assets/55282486/29306711-6f1c-445e-bac0-abfa7b6aa9d8)

**Comment by ANTIBigBoss** [comment]
Awesome glad it fixed it! It looks like it was some accessibilty setting I had when I was first starting to work on the project or something I ended up just deleting the form and remaking it which was a much easier solve than I thought it'd be haha. Thanks for confirming with me!
